### PR TITLE
Problem: Tests are failing (#286)

### PR DESCRIPTION
**Pull request by anbud**
Solution: Fix failing client side tests.

### CODE REVIEW

**Comment by gazhayes** [comment]
@anbud still failing :(

**Comment by anbud** [comment]
Hmm, this is weird, client side ones are fixed, but some server side ones are failing now. They weren't failing when I was fixing them. 

I'll check it out when I get home. :)

**Comment by anbud** [comment]
Since a lot of things have changed, merge this one and I'll send another one that fixes server-side tests. :)
@gazhayes, @samuelralak, @MadanBhandari

**Comment by samuelralak** [comment]
cool. merging it as soon as I get home

**Pull request merged**
