### PR TITLE
Problem: Horizontal Scroll issue and breadcrumbs helper (#524)

### PR DESCRIPTION
**Pull request by akatrodiya**

### CODE REVIEW

**Comment by gazhayes** [comment]
Ajay could you edit the commit message (problem:....), check the C4 for details.

**Comment by akatrodiya** [comment]
Hi @gazhayes I did some research to update the commit message after commit is already done.. but it's taking time.. so, from next commit I'll always take care of commit message.. can you approve for this time?

**Comment by geekyd** [comment]
@akatrodiya To update the commit message simply use `git commit --amend`. To better understand this have a look at https://www.atlassian.com/git/tutorials/rewriting-history. I hope this helps :)

**Comment by geekyd** [comment]
@akatrodiya Try this it should work

**Reset the head to the original commit(https://github.com/EmurgoHK/cardanoupdate/pull/525/commits/0cec4ad682e565991929cff5cfbe7217b94083cf)** 
`git reset --hard 0cec4ad682e565991929cff5cfbe7217b94083cf` 

**Change the commit message here**
`git commit --amend`

**Force push to your branch**
`git push -f origin scroll_ui`

**Comment by akatrodiya** [comment]
@geekyd done, Thanks

**Comment by gazhayes** [comment]
This isn't really C4 but I'm merging it anyway. Close, but you can do better ;)

**Pull request merged**
