### PR TITLE
problem: project headline/name can be too long #190

### PR DESCRIPTION
**Pull request by omar20261**
solution:  change limit from 100 to 25 chars in maxCharValue in forntend and in ValidatedMethod in backend

### CODE REVIEW

**Comment by gazhayes** [comment]
@omar20261 still conflicts. Ping me when resolved so I merge it immediately before new conflicts get created again

**Comment by gazhayes** [comment]
@omar20261 still conflicts. Ping me when resolved so I merge it immediately before new conflicts get created again

**Comment by gazhayes** [comment]
ping @omar20261 new conflicts probably created when something else was merged. Ping me when you fix this one and I'll merge it immediately before new conflicts get generated.

**Comment by anbud** [comment]
Ping me as well, if @gazhayes doesn't happen to be here. :)

**Comment by gazhayes** [comment]
Looks like this has caused multiple issues and reverted a number of other PRs. It has to be reverted.

**Pull request merged**
