### PR TITLE
problem: not totally clear what globe icon is for #223

### PR DESCRIPTION
**Pull request by samuelralak**
solution: changed website icon from globe to external-link icon. added tooltip

### CODE REVIEW

**Comment by anbud** [comment]
@samuelralak, conflicts. :)

**Comment by gazhayes** [comment]
@samuelralak the conflicts look like they might be a bit nasty, probably have to copy/paste changes into a new commit.

**Comment by samuelralak** [comment]
oh, will take a look later on today.

**Comment by gazhayes** [comment]
@anbud I can't merge this on my phone for some reason.

**Comment by gazhayes** [comment]
Ah, because conflicts of course

**Pull request closed without merging**
