### PR TITLE
problem: no breadcrumbs

### PR DESCRIPTION
**Pull request by AshHimself**
solution: added breadcrumbs for better UX #287

### CODE REVIEW

**Comment by gazhayes** [comment]
Holy crap a passing test! They've been rare over the last week or so.

**Comment by AshHimself** [comment]
bahahaha I can't wait to bonus time!!

**Comment by gazhayes** [comment]
@AshHimself looks like it's not actually working on production

**Comment by AshHimself** [comment]
Forgive me but what is the production URL?

**Comment by gazhayes** [comment]
cardanoupdate.space

**Comment by AshHimself** [comment]
Looks like I missed that routes.js actually moved from client to both

**Pull request merged**
