### PR TITLE
problem: no Warnings section #218

### PR DESCRIPTION
**Pull request by geekyd**
solution: Adds a warning section with attributes similar to project section

### CODE REVIEW

**Comment by geekyd** [comment]
Looking into the tests

**Comment by anbud** [comment]
If they keep failing, feel free to ping me, I'll take a look. :)

**Comment by geekyd** [comment]
@anbud The frontend tests are not running can you clear the cache from travis?

**Comment by samuelralak** [comment]
cleared cache and restarted build

**Comment by gazhayes** [comment]
Merged anyway

**Pull request merged**
